# Generated by Django 5.1.7 on 2025-03-14 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('base_plate_thickness', models.FloatField()),
                ('flange_thickness', models.FloatField()),
                ('web_thickness', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='beam',
            old_name='material',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='load',
            old_name='force',
            new_name='bolt_diameter',
        ),
        migrations.RenameField(
            model_name='load',
            old_name='position',
            new_name='plate_thickness',
        ),
        migrations.AddField(
            model_name='beam',
            name='height',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='beam',
            name='width',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='load',
            name='bolt_grade',
            field=models.CharField(default='A325', max_length=50),
        ),
        migrations.AlterField(
            model_name='beam',
            name='length',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='load',
            name='column',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='core_api.column'),
            preserve_default=False,
        ),
    ]
